PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMVC1MM0001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMVC1MM0001-MATNR .
    FIELD ZMVC1MM0001-MAKTX .
    FIELD ZMVC1MM0001-MTART .
    FIELD ZMVC1MM0001-MATKL .
    FIELD ZMVC1MM0001-NTGEW .
    FIELD ZMVC1MM0001-GEWEI .
    FIELD ZMVC1MM0001-ERDAT .
    FIELD ZMVC1MM0001-ERNAM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMVC1MM0001-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
